fix the compilation error caused by CONFIG_DISABLE_SIGNALS
The commit 'add support for CONFIG_DISABLE_SIGNALS' led to:

undefined reference to `signal'
undefined reference to `sigaction'

Signed-off-by: v-tangmeng <v-tangmeng@xiaomi.com>