fix builtin_list.c:58:10: fatal error: builtin_proto.h: No such file or directory (#2)
Make builtin_list.c instead of builtin_list.o depend on builtin_proto.h and builtin_proto.c